# Generated by Django 4.2.1 on 2023-05-17 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_timetracking_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 17, 43, 33, 613394, tzinfo=datetime.timezone.utc)),
        ),
    ]
