# Generated by Django 4.2.1 on 2023-05-18 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_alter_timetracking_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 18, 2, 30, 169297, tzinfo=datetime.timezone.utc)),
        ),
    ]
