# Generated by Django 3.0.2 on 2020-01-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stype', models.BooleanField()),
                ('prev_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('prev_longitude', models.IntegerField(default=0)),
                ('prev_latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('latitude', models.IntegerField(default=0)),
                ('cud', models.CharField(max_length=1)),
            ],
        ),
    ]
