# Generated by Django 3.0.2 on 2020-01-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='desc',
            field=models.CharField(default='Default', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
