# Generated by Django 3.0.2 on 2020-01-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0002_suggestion_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='cud',
            field=models.IntegerField(choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')]),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='stype',
            field=models.IntegerField(choices=[(1, 'Event'), (2, 'Place')]),
        ),
    ]
