# Generated by Django 3.0.2 on 2020-01-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0003_auto_20200131_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='prev_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='prev_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='prev_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
