# Generated by Django 3.0.2 on 2020-01-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0004_auto_20200131_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='prev_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='prev_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
