# Generated by Django 3.0.2 on 2020-02-02 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0005_auto_20200131_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
