# Generated by Django 3.0.3 on 2020-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_map', '0006_suggestion_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='prev_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='prev_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='stype',
            field=models.IntegerField(choices=[(1, 'Event'), (2, 'Health'), (3, 'Food'), (4, 'Finance'), (5, 'Store'), (6, 'Etc')]),
        ),
    ]
